content(Webseite - Home): Timeline Inhalte wurden überarbeitet und aktualisiert.
Cubyx-Network/website pull request #171
Opened 2023-10-29 21:49 UTC by LinkLuigiMaster

change(Webseite - Home): Es können jetzt auch URLs mit eingebunden werden zu den jeweiligen Timeline Einträgen.

2023-10-30 08:27 UTC, SachsenspieltCoding requested changes

2023-10-30 08:27 UTC, SachsenspieltCoding commented on src/components/Timeline/AboutTimeline.svelte
> +	const discordString = 'Discord ➚↗';
Wozu wird diese Variable gebraucht?

2023-10-30 08:27 UTC, SachsenspieltCoding commented on src/components/Timeline/AboutTimeline.svelte
> +		},
Warum?

2023-10-30 08:27 UTC, SachsenspieltCoding commented on src/components/Timeline/AboutTimeline.svelte
> +		},
Wenn es nicht geprüft ist, dann können wir es eigentlich auch rausnehmen, oder?

2023-10-30 08:27 UTC, SachsenspieltCoding commented on src/components/Timeline/AboutTimeline.svelte
> +		}, */
Obsoleter Kommentar, gleiches wie beim anderen nicht geprüften.

2023-10-30 08:27 UTC, SachsenspieltCoding commented on src/components/Timeline/AboutTimeline.svelte
> +		} */
Gleiche wie oben

2023-10-30 08:27 UTC, SachsenspieltCoding commented on src/components/Timeline/AboutTimeline.svelte
> +		} */
Solche Templates sind aufgrund der Typisierung überflüssig, der Kommentar kann also eigentlich auch raus

2023-10-30 08:27 UTC, SachsenspieltCoding commented on src/components/Timeline/Timeline.svelte
> +		urllink?: string;
Die Bezeichnung ist meiner Meinung etwas komisch.
Ich glaube `url`, `href`, oder `link` würde hier eher passen

2023-10-30 08:27 UTC, SachsenspieltCoding commented on src/components/Timeline/TimelineItem.svelte
> +import type { TimelineItemType } from "./Timeline.svelte";
Formatierung scheint nicht ganz korrekt, einfach mal `npm run format` ausführen

2023-10-30 08:27 UTC, SachsenspieltCoding commented on src/components/Timeline/TimelineItem.svelte
> +		<p class="whitespace-normal break-words font-medium">{item.title}⠀{#if item.urllink}<a href='{item.urllink}'>➚</a>{/if}</p>
Anstatt des Unicode Zeichens, könnte auch einfach ein Icon von Fontawesome genutzt werden, dann ist sicher, dass es überall gleich aussieht.
Eventuell `faLink`?
![grafik](https://github.com/Cubyx-Network/website/assets/59836848/67170a7d-4a1b-4225-963f-982ce7ec842d)

2023-10-30 15:52 UTC, LinkLuigiMaster commented on src/components/Timeline/AboutTimeline.svelte
> +	const discordString = 'Discord ➚↗';
Kommt erstmal wieder raus.

2023-10-30 15:52 UTC, LinkLuigiMaster commented on src/components/Timeline/AboutTimeline.svelte
> +	const discordString = 'Discord ➚↗';
War für ein Feature gedacht, welches erstmal wieder rausfällt bzw. verworfen wurde.

2023-10-30 15:54 UTC, LinkLuigiMaster commented on src/components/Timeline/AboutTimeline.svelte
> +		},
Weil da fehlt halt noch Inhalt, den ich noch nicht bestimmen konnte.

2023-10-30 15:55 UTC, SachsenspieltCoding commented on src/components/Timeline/AboutTimeline.svelte
> +		},
> Weil da fehlt halt noch Inhalt, den ich noch nicht bestimmen konnte.

Aber dann muss es doch auch nicht auf der Seite stehen, oder?

2023-10-30 15:56 UTC, LinkLuigiMaster commented on src/components/Timeline/AboutTimeline.svelte
> +		},
Falls ich keine Bestätigung bekomme von den die es Überprüfen sollen oder es selber nicht so finde, fällt es raus.

2023-10-30 15:57 UTC, LinkLuigiMaster commented on src/components/Timeline/AboutTimeline.svelte
> +		} */
Macht es jedoch einfacher.

2023-10-30 16:02 UTC, LinkLuigiMaster commented on src/components/Timeline/Timeline.svelte
> +		urllink?: string;
Ich nehme href, da link und url ungünstig gewählt sind.
Aber href geht klar.

2023-10-30 16:06 UTC, SachsenspieltCoding commented on src/components/Timeline/AboutTimeline.svelte
> +		} */
Für wen konkret? Im Zweifel kopiert man sich eben den Eintrag von dadrüber.
Ich finde solche Kommentare blähen den Code unnötig auf

2023-11-05 23:00 UTC, LinkLuigiMaster commented
Also die Funktionen wurde, wie heute abgesprochen, noch fertig integriert und die überflüssigen Kommentare aka. Inhalte von der Timeline wurde lokal bei mir abgelegt und aus dem Code entfernt. 
Jetzt müssen nur noch der Style und die Texte angepasst werden.

Das überlasse ich dir Sachsen.

2023-11-06 16:50 UTC, SachsenspieltCoding approved these changes

2023-11-06 16:51 UTC, merged